#!/bin/bash


_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $LionX_REPO == "LionXBot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RlYW1MaW9uWC9MaW9uLVgvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $LionX_REPO == "LionXbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RlYW1MaW9uWC9MaW9uLVgvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $LionX_REPO =~ $regex ]]
    then
        if [[ $LionX_REPO_BRANCH ]]
        then
            echo "${LionX_REPO}/archive/${LionX_REPO_BRANCH}.zip"
        else
            echo "${LionX_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RlYW1MaW9uWC9MaW9uLVgvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}


start_bot () {
    local zippath
    zippath="myLionXbot.zip"
    echo "  Downloading source code ..."
    wget -q $(_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    LionXPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "  Processing Codes..."
    rm -rf "$zippath"
    sleep 5
    cd $LionXPATH
    echo "  • Starting LionXBot •  "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m LionXbot
}

start_bot
