#!/bin/bash


_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $LIONX_REPO == "LIONX" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RlYW1MaW9uWC9MaW9uLVgvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $LIONX_REPO == "LIONX" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RlYW1MaW9uWC9MaW9uLVgvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $LIONX_REPO =~ $regex ]]
    then
        if [[ $LIONX_REPO_BRANCH ]]
        then
            echo "${LIONX_REPO}/archive/${LIONX_REPO_BRANCH}.zip"
        else
            echo "${LIONX_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RlYW1MaW9uWC9MaW9uLVgvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}


start_bot () {
    local zippath
    zippath="myLIONX.zip"
    echo "  Downloading source code ..."
    wget -q $(_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    LIONXPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "  Processing Codes..."
    rm -rf "$zippath"
    sleep 5
    cd $LIONXPATH
    echo "  • Starting LIONX •  "

    python3 ../setup/updater.py ../LionXsetup.txt LionXsetup.txt
    python3 -m LIONX
}

start_bot
